name: Auto Publish Python Package

on:
  push:
    tags:
      - "v*"        # Run when you push a tag like v0.1.0
  workflow_dispatch: # Allow manual run

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only need read perms for repo

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build toml

      - name: Bump version with post release
        id: bump
        run: |
          BASE_VERSION="0.1.0"
          FILE="pyproject.toml"

          # extract current version
          CURRENT_VERSION=$(grep '^version' $FILE | cut -d'"' -f2)

          if [[ "$CURRENT_VERSION" == "$BASE_VERSION" ]]; then
            NEW_VERSION="${BASE_VERSION}.post1"
          elif [[ "$CURRENT_VERSION" =~ ^${BASE_VERSION}\.post([0-9]+)$ ]]; then
            NUM=${BASH_REMATCH[1]}
            NEXT=$((NUM+1))
            NEW_VERSION="${BASE_VERSION}.post${NEXT}"
          else
            NEW_VERSION=$CURRENT_VERSION
          fi

          echo "Updating version to $NEW_VERSION"
          sed -i "s/version = \".*\"/version = \"${NEW_VERSION}\"/" $FILE
          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build package
        run: python -m build

      - name: Publish to PyPI using API token
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__   # <--- force API token auth
          password: ${{ secrets.PYPI_API_TOKEN }}
